use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let assets_src = manifest_dir.join("assets");
    println!("cargo:rerun-if-changed={}", assets_src.display());
    copy_runtime_assets(manifest_dir);

    let assets_manifest = manifest_dir.join("assets/manifest.toml");
    println!("cargo:rerun-if-changed={}", assets_manifest.display());

    let manifest: toml::Value = toml::from_str(
        &fs::read_to_string(&assets_manifest).expect("read assets/manifest.toml"),
    )
    .expect("parse assets/manifest.toml");

    let texture_section = generate_texture_section(
        manifest
            .get("texture")
            .and_then(|value| value.as_array())
            .cloned()
            .unwrap_or_default()
            .as_slice(),
    );

    let map_section = generate_map_section(
        manifest
            .get("map")
            .and_then(|value| value.as_array())
            .cloned()
            .unwrap_or_default()
            .as_slice(),
    );

    let shader_section = generate_shader_section(
        manifest
            .get("shader")
            .and_then(|value| value.as_array())
            .cloned()
            .unwrap_or_default()
            .as_slice(),
    );

    let sound_section = generate_sound_section(
        manifest
            .get("sound")
            .and_then(|value| value.as_array())
            .cloned()
            .unwrap_or_default()
            .as_slice(),
        manifest_dir,
    );

    let sound_preset_section = generate_sound_preset_section(
        manifest
            .get("sound_preset")
            .and_then(|value| value.as_array())
            .cloned()
            .unwrap_or_default()
            .as_slice(),
        manifest_dir,
    );

    let config_section = generate_config_section(
        manifest
            .get("config")
            .and_then(|value| value.as_array())
            .cloned()
            .unwrap_or_default()
            .as_slice(),
        manifest_dir,
    );

    let generated = format!(
        r#"// @generated by build.rs — do not edit

use crate::resources::uid::{{ConfigManifestEntry, MapManifestEntry, ShaderManifestEntry, SoundManifestEntry, SoundPresetManifestEntry, TextureManifestEntry}};

{texture_section}

{map_section}

{shader_section}

{sound_section}

{sound_preset_section}

{config_section}
"#
    );

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(Path::new(&out_dir).join("asset_ids.rs"), generated).expect("write asset_ids.rs");
}

fn generate_texture_section(entries: &[toml::Value]) -> String {
    let mut constants = String::new();
    let mut manifest_entries = String::new();

    for (index, entry) in entries.iter().enumerate() {
        let name = required_str(entry, "name", "texture");
        let path = required_str(entry, "path", "texture");
        let const_name = name.to_ascii_uppercase();

        constants.push_str(&format!(
            "pub const {const_name}: TextureUid = TextureUid::new({index});\n"
        ));
        manifest_entries.push_str(&format!(
            "TextureManifestEntry {{ uid: texture::{const_name}, path: \"{path}\" }},\n"
        ));
    }

    format!(
        r#"pub mod texture {{
    use crate::resources::uid::TextureUid;

{constants}}}

pub const TEXTURES: &[TextureManifestEntry] = &[
{manifest_entries}];"#
    )
}

fn generate_map_section(entries: &[toml::Value]) -> String {
    let mut constants = String::new();
    let mut manifest_entries = String::new();

    for (index, entry) in entries.iter().enumerate() {
        let name = required_str(entry, "name", "map");
        let path = required_str(entry, "path", "map");
        let const_name = name.to_ascii_uppercase();

        constants.push_str(&format!(
            "pub const {const_name}: MapUid = MapUid::new({index});\n"
        ));
        manifest_entries.push_str(&format!(
            "MapManifestEntry {{ uid: map::{const_name}, path: \"{path}\" }},\n"
        ));
    }

    format!(
        r#"pub mod map {{
    use crate::resources::uid::MapUid;

{constants}}}

pub const MAPS: &[MapManifestEntry] = &[
{manifest_entries}];"#
    )
}

fn generate_shader_section(entries: &[toml::Value]) -> String {
    let mut constants = String::new();
    let mut manifest_entries = String::new();

    for (index, entry) in entries.iter().enumerate() {
        let name = required_str(entry, "name", "shader");
        let vert = required_str(entry, "vert", "shader");
        let frag = required_str(entry, "frag", "shader");
        let const_name = name.to_ascii_uppercase();

        constants.push_str(&format!(
            "pub const {const_name}: ShaderUid = ShaderUid::new({index});\n"
        ));
        manifest_entries.push_str(&format!(
            "ShaderManifestEntry {{ uid: shader::{const_name}, vert: \"{vert}\", frag: \"{frag}\" }},\n"
        ));
    }

    format!(
        r#"pub mod shader {{
    use crate::resources::uid::ShaderUid;

{constants}}}

pub const SHADERS: &[ShaderManifestEntry] = &[
{manifest_entries}];"#
    )
}

fn generate_sound_section(entries: &[toml::Value], manifest_dir: &Path) -> String {
    let mut constants = String::new();
    let mut manifest_entries = String::new();

    for (index, entry) in entries.iter().enumerate() {
        let name = required_str(entry, "name", "sound");
        let path = required_str(entry, "path", "sound");
        let const_name = name.to_ascii_uppercase();

        let sound_path = manifest_dir.join("assets").join(path);
        println!("cargo:rerun-if-changed={}", sound_path.display());

        constants.push_str(&format!(
            "pub const {const_name}: SoundUid = SoundUid::new({index});\n"
        ));
        manifest_entries.push_str(&format!(
            "SoundManifestEntry {{ uid: sound::{const_name}, name: \"{name}\", path: \"{path}\" }},\n"
        ));
    }

    format!(
        r#"pub mod sound {{
    use crate::resources::SoundUid;

{constants}}}

pub const SOUNDS: &[SoundManifestEntry] = &[
{manifest_entries}];"#
    )
}

fn generate_sound_preset_section(entries: &[toml::Value], manifest_dir: &Path) -> String {
    let mut constants = String::new();
    let mut manifest_entries = String::new();

    for (index, entry) in entries.iter().enumerate() {
        let name = required_str(entry, "name", "sound_preset");
        let path = required_str(entry, "path", "sound_preset");
        let const_name = name.to_ascii_uppercase();

        let preset_path = manifest_dir.join("assets").join(path);
        println!("cargo:rerun-if-changed={}", preset_path.display());

        constants.push_str(&format!(
            "pub const {const_name}: SoundPresetUid = SoundPresetUid::new({index});\n"
        ));
        manifest_entries.push_str(&format!(
            "SoundPresetManifestEntry {{ uid: sound_preset::{const_name}, name: \"{name}\", path: \"{path}\" }},\n"
        ));
    }

    format!(
        r#"pub mod sound_preset {{
    use crate::resources::SoundPresetUid;

{constants}}}

pub const SOUND_PRESETS: &[SoundPresetManifestEntry] = &[
{manifest_entries}];"#
    )
}

fn generate_config_section(entries: &[toml::Value], manifest_dir: &Path) -> String {
    let mut constants = String::new();
    let mut manifest_entries = String::new();

    for (index, entry) in entries.iter().enumerate() {
        let name = required_str(entry, "name", "config");
        let path = required_str(entry, "path", "config");
        let const_name = name.to_ascii_uppercase();

        let config_path = manifest_dir.join("assets").join(path);
        println!("cargo:rerun-if-changed={}", config_path.display());

        constants.push_str(&format!(
            "pub const {const_name}: ConfigUid = ConfigUid::new({index});\n"
        ));
        manifest_entries.push_str(&format!(
            "ConfigManifestEntry {{ uid: config::{const_name}, path: \"{path}\" }},\n"
        ));
    }

    format!(
        r#"pub mod config {{
    use crate::resources::uid::ConfigUid;

{constants}}}

pub const CONFIGS: &[ConfigManifestEntry] = &[
{manifest_entries}];"#
    )
}

fn required_str<'a>(entry: &'a toml::Value, key: &str, kind: &str) -> &'a str {
    entry
        .get(key)
        .and_then(|value| value.as_str())
        .unwrap_or_else(|| panic!("{kind} entry requires {key}"))
}

fn copy_runtime_assets(manifest_dir: &Path) {
    let src = manifest_dir.join("assets");
    let target_root = env::var("CARGO_TARGET_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| manifest_dir.join("target"));
    let profile = env::var("PROFILE").expect("PROFILE set by Cargo");
    let dst = target_root.join(profile).join("assets");

    copy_dir_all(&src, &dst).expect("copy runtime assets into target output");
}

fn copy_dir_all(src: &Path, dst: &Path) -> std::io::Result<()> {
    if !src.is_dir() {
        return Err(std::io::Error::new(
            std::io::ErrorKind::NotFound,
            format!("assets source directory not found: {}", src.display()),
        ));
    }

    fs::create_dir_all(dst)?;
    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let file_type = entry.file_type()?;
        let from = entry.path();
        let to = dst.join(entry.file_name());
        if file_type.is_dir() {
            copy_dir_all(&from, &to)?;
        } else {
            if let Some(parent) = to.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::copy(&from, &to)?;
        }
    }
    Ok(())
}
