use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let assets_manifest = manifest_dir.join("assets/manifest.toml");
    println!("cargo:rerun-if-changed={}", assets_manifest.display());

    let manifest: toml::Value = toml::from_str(
        &fs::read_to_string(&assets_manifest).expect("read assets/manifest.toml"),
    )
    .expect("parse assets/manifest.toml");

    let texture_section = generate_texture_section(
        manifest
            .get("texture")
            .and_then(|value| value.as_array())
            .cloned()
            .unwrap_or_default()
            .as_slice(),
    );

    let map_section = generate_map_section(
        manifest
            .get("map")
            .and_then(|value| value.as_array())
            .cloned()
            .unwrap_or_default()
            .as_slice(),
    );

    let shader_section = generate_shader_section(
        manifest
            .get("shader")
            .and_then(|value| value.as_array())
            .cloned()
            .unwrap_or_default()
            .as_slice(),
    );

    let generated = format!(
        r#"// @generated by build.rs — do not edit

use crate::resources::uid::{{MapManifestEntry, ShaderManifestEntry, TextureManifestEntry}};

{texture_section}

{map_section}

{shader_section}
"#
    );

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(Path::new(&out_dir).join("asset_ids.rs"), generated).expect("write asset_ids.rs");
}

fn generate_texture_section(entries: &[toml::Value]) -> String {
    let mut constants = String::new();
    let mut manifest_entries = String::new();

    for (index, entry) in entries.iter().enumerate() {
        let name = required_str(entry, "name", "texture");
        let path = required_str(entry, "path", "texture");
        let const_name = name.to_ascii_uppercase();

        constants.push_str(&format!(
            "pub const {const_name}: TextureUid = TextureUid::new({index});\n"
        ));
        manifest_entries.push_str(&format!(
            "TextureManifestEntry {{ uid: texture::{const_name}, path: \"{path}\" }},\n"
        ));
    }

    format!(
        r#"pub mod texture {{
    use crate::resources::uid::TextureUid;

{constants}}}

pub const TEXTURES: &[TextureManifestEntry] = &[
{manifest_entries}];"#
    )
}

fn generate_map_section(entries: &[toml::Value]) -> String {
    let mut constants = String::new();
    let mut manifest_entries = String::new();

    for (index, entry) in entries.iter().enumerate() {
        let name = required_str(entry, "name", "map");
        let path = required_str(entry, "path", "map");
        let const_name = name.to_ascii_uppercase();

        constants.push_str(&format!(
            "pub const {const_name}: MapUid = MapUid::new({index});\n"
        ));
        manifest_entries.push_str(&format!(
            "MapManifestEntry {{ uid: map::{const_name}, path: \"{path}\" }},\n"
        ));
    }

    format!(
        r#"pub mod map {{
    use crate::resources::uid::MapUid;

{constants}}}

pub const MAPS: &[MapManifestEntry] = &[
{manifest_entries}];"#
    )
}

fn generate_shader_section(entries: &[toml::Value]) -> String {
    let mut constants = String::new();
    let mut manifest_entries = String::new();

    for (index, entry) in entries.iter().enumerate() {
        let name = required_str(entry, "name", "shader");
        let vert = required_str(entry, "vert", "shader");
        let frag = required_str(entry, "frag", "shader");
        let const_name = name.to_ascii_uppercase();

        constants.push_str(&format!(
            "pub const {const_name}: ShaderUid = ShaderUid::new({index});\n"
        ));
        manifest_entries.push_str(&format!(
            "ShaderManifestEntry {{ uid: shader::{const_name}, vert: \"{vert}\", frag: \"{frag}\" }},\n"
        ));
    }

    format!(
        r#"pub mod shader {{
    use crate::resources::uid::ShaderUid;

{constants}}}

pub const SHADERS: &[ShaderManifestEntry] = &[
{manifest_entries}];"#
    )
}

fn required_str<'a>(entry: &'a toml::Value, key: &str, kind: &str) -> &'a str {
    entry
        .get(key)
        .and_then(|value| value.as_str())
        .unwrap_or_else(|| panic!("{kind} entry requires {key}"))
}
