use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let assets_manifest = manifest_dir.join("assets/manifest.toml");
    println!("cargo:rerun-if-changed={}", assets_manifest.display());

    let manifest: toml::Value = toml::from_str(
        &fs::read_to_string(&assets_manifest).expect("read assets/manifest.toml"),
    )
    .expect("parse assets/manifest.toml");

    let textures = manifest
        .get("texture")
        .and_then(|value| value.as_array())
        .cloned()
        .unwrap_or_default();

    let mut texture_entries = String::new();
    let mut texture_constants = String::new();

    for (index, entry) in textures.iter().enumerate() {
        let name = entry
            .get("name")
            .and_then(|value| value.as_str())
            .expect("texture entry requires name");
        let path = entry
            .get("path")
            .and_then(|value| value.as_str())
            .expect("texture entry requires path");

        let const_name = name.to_ascii_uppercase();
        texture_constants.push_str(&format!(
            "pub const {const_name}: TextureUid = TextureUid::new({index});\n"
        ));
        texture_entries.push_str(&format!(
            "TextureManifestEntry {{ uid: texture::{const_name}, path: \"{path}\" }},\n"
        ));
    }

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let generated = format!(
        r#"// @generated by build.rs — do not edit

use crate::resources::uid::TextureManifestEntry;

pub mod texture {{
    use crate::resources::uid::TextureUid;

{texture_constants}}}

pub const TEXTURES: &[TextureManifestEntry] = &[
{texture_entries}];
"#
    );

    fs::write(Path::new(&out_dir).join("asset_ids.rs"), generated).expect("write asset_ids.rs");
}
